expense_analysis:
  description: >
    Analyze transaction data to:
    - Categorize expenses into predefined budget categories
    - Identify unusual spending patterns
    - Detect recurring subscriptions
    - Compare actual spending against budget targets
    - Suggest budget adjustments and savings opportunities
    - Use historical spending data and financial goals to provide
    personalized recommendations.
    
  expected_output: >
    Detailed expense analysis with categorization, anomaly detection,
    and personalized financial recommendations.

budget_management:
  description: >
    Generate financial overview including:
    - Monthly income vs expense summary
    - Budget category adherence analysis
    - Debt-to-income ratio tracking
    - Emergency fund progress
    - Long-term goal tracking (retirement, investments)
    - Format results in clear tables for visualization.

    These tables will serve as the foundation for generating charts in the next
    task.
  expected_output: >
    Structured financial summary tables showing key metrics and
    progress toward financial goals.

financial_visualization:
  description: >
    Create visual representations of financial health:
    - Spending category breakdown (pie/bar charts)
    - Monthly spending trends (line charts)
    - Budget vs actual comparisons (dual-axis charts)
    - Net worth progression (waterfall chart)
    - Goal progress tracking (thermometer charts)
    - Save visualizations as images and generate embeddable URLs.

    Save the charts as image files in the current directory.

    Ensure that the charts are saved as image files, and generate URLs for these
    images so they can be easily embedded into the final report.
  expected_output: >
    Set of financial charts providing at-a-glance understanding of
    financial status and goal progress.


final_report_assembly:
  description: >
    Compile comprehensive financial report containing:
    - Monthly financial snapshot
    - Expense categorization analysis
    - Budget adherence assessment
    - Debt management overview
    - Goal progress tracking
    - Recommended financial actions
    - Integrate tables and visualizations with explanatory text.
    Format for easy understanding by non-financial users.

    The report should have tables and relevant charts side by side with an
    appropriate size.

    The report should be formatted for easy consumption by stakeholders,
    providing valuable insights into the performance of the support system and
    areas for improvement.
  expected_output: >
    Professional financial report with integrated data visualizations
    and actionable recommendations in clear markdown format.
    Don't add '```' or '```markdown' to the report.
